export enum LoadingState {
  NO_ACTION_PERFORMED = "TC_LOADING_STATE_NO_ACTION_PERFORMED",
  LOADING = "TC_LOADING_STATE_LOADING",
  UNSUCCESSFUL_TASK = "TC_LOADING_STATE_UNSUCCESSFUL_TASK",
  SUCCESSFUL_TASK = "TC_LOADING_STATE_SUCCESSFUL_TASK",
  WORK_DONE = "TC_LOADING_STATE_WORK_DONE"
}
