export enum AppointmentNotificationCodeType {
  APPOINTMENT_SCHEDULED = "APPOINTMENT_SCHEDULED",
  APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED",
  APPOINTMENT_CANCELED = "APPOINTMENT_CANCELED",
  APPOINTMENT_REMINDER = "APPOINTMENT_REMINDER",
  APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
}
