export enum GeneralNotificationCodeType {
  GENERAL_WELCOME = "GENERAL_WELCOME",
  GENERAL_NEWS = "GENERAL_NEWS",
  GENERAL_PROMOTION = "GENERAL_PROMOTION",
  GENERAL_SERVICE_UPDATE = "GENERAL_SERVICE_UPDATE"
}
