export enum NotificationType {
  APPOINTMENT_NOTIFICATION = "APPOINTMENT_NOTIFICATION",
  PAYMENT_NOTIFICATION = "PAYMENT_NOTIFICATION",
  SYSTEM_NOTIFICATION = "SYSTEM_NOTIFICATION",
  GENERAL_NOTIFICATION = "GENERAL_NOTIFICATION"
}
