export enum SystemNotificationCodeType {
  SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE",
  SYSTEM_ERROR = "SYSTEM_ERROR",
  SYSTEM_UPDATE = "SYSTEM_UPDATE",
  SYSTEM_BACKUP = "SYSTEM_BACKUP",
  SYSTEM_SECURITY = "SYSTEM_SECURITY",
  SYSTEM_THRESHOLD = "SYSTEM_THRESHOLD",
  SYSTEM_CONFIG_CHANGE = "SYSTEM_CONFIG_CHANGE"
}
