services:
  database:
    image: postgres
    container_name: appointment_scheduler_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
    - scheduling-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment_scheduler_api
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${DEFAULT_DB_CONNECTION}
    depends_on:
      - database
    networks:
      - scheduling-net


volumes:
  postgres-data:

networks:
  scheduling-net:
    driver: bridge