namespace AppointmentSchedulerAPI.layers.CrossCuttingLayer.Communication.Model
{
    public enum MessageCodeType
    {
        OK,
        SUCCESS_OPERATION,
        DATA_FOUND,
        DATA_NOT_FOUND,
        DATA_UPDATED,
        SERVER_ERROR,
        REGISTER_ERROR,
        INVALID_CREDENTIALS,
        UNAUTHORIZED,
        NULL_VALUE_IS_PRESENT,
        CLIENT_NOT_FOUND,
        SERVICE_NOT_FOUND,
        ASSISTANT_NOT_FOUND,
        USERNAME_ALREADY_REGISTERED,
        EMAIL_ALREADY_REGISTERED,
        SERVICE_NAME_ALREADY_REGISTERED,
        PHONE_NUMBER_ALREADY_REGISTERED,
        AVAILABILITY_TIME_SLOT_NOT_AVAILABLE,
        APPOINTMENT_TIME_SLOT_NOT_AVAILABLE,
    }
}
