using Microsoft.OpenApi.Writers;

namespace AppointmentSchedulerAPI.layers.CrossCuttingLayer.Communication.Model
{
    public static class ValidationCodeType
    {
        // Required
        public const string VALIDATION_ACCOUNT_FIELD_REQUIRED = "VALIDATION_ACCOUNT_FIELD_REQUIRED";
        public const string VALIDATION_PASSWORD_FIELD_REQUIRED = "VALIDATION_PASSWORD_FIELD_REQUIRED";
        public const string VALIDATION_EMAIL_FIELD_REQUIRED = "VALIDATION_EMAIL_FIELD_REQUIRED";
        public const string VALIDATION_USERNAME_FIELD_REQUIRED = "VALIDATION_USERNAME_FIELD_REQUIRED";
        public const string VALIDATION_PHONE_NUMBER_FIELD_REQUIRED = "VALIDATION_PHONE_NUMBER_FIELD_REQUIRED";
        public const string VALIDATION_NAME_FIELD_REQUIRED = "VALIDATION_NAME_FIELD_REQUIRED";


        // Format
        public const string VALIDATION_EMAIL_INVALID_FORMAT = "VALIDATION_EMAIL_INVALID_FORMAT";
        public const string VALIDATION_PASSWORD_INVALID_FORMAT = "VALIDATION_PASSWORD_INVALID_FORMAT";
        public const string VALIDATION_PHONE_NUMBER_INVALID_FORMAT = "VALIDATION_PHONE_NUMBER_INVALID_FORMAT";
        // Type
        public const string VALIDATION_PASSWORD_INVALID_TYPE = "VALIDATION_PASSWORD_INVALID_TYPE";


        // Violations
        public const string VALIDATION_CHARACTERS_NOT_ALLOWED_VIOLATION = "VALIDATION_CHARACTERS_NOT_ALLOWED_VIOLATION";
        public const string VALIDATION_USERNAME_CHARACTERS_NOT_ALLOWED_VIOLATION = "VALIDATION_USERNAME_CHARACTERS_NOT_ALLOWED_VIOLATION";
        public const string VALIDATION_NAME_CHARACTERS_NOT_ALLOWED_VIOLATION = "VALIDATION_NAME_CHARACTERS_NOT_ALLOWED_VIOLATION";
        public const string VALIDATION_EMAIL_MAX_LIMIT_VIOLATION = "VALIDATION_EMAIL_MAX_LIMIT_VIOLATION";
        public const string VALIDATION_EMAIL_MIN_LIMIT_VIOLATION = "VALIDATION_EMAIL_MIN_LIMIT_VIOLATION";
        public const string VALIDATION_PASSWORD_MAX_LIMIT_VIOLATION = "VALIDATION_PASSWORD_MAX_LIMIT_VIOLATION";
        public const string VALIDATION_PASSWORD_MIN_LIMIT_VIOLATION = "VALIDATION_PASSWORD_MIN_LIMIT_VIOLATION";
        public const string VALIDATION_USERNAME_MAX_LIMIT_VIOLATION = "VALIDATION_USERNAME_MAX_LIMIT_VIOLATION";
        public const string VALIDATION_USERNAME_MIN_LIMIT_VIOLATION = "VALIDATION_USERNAME_MIN_LIMIT_VIOLATION";
        public const string VALIDATION_NAME_MAX_LIMIT_VIOLATION = "VALIDATION_NAME_MAX_LIMIT_VIOLATION";
        public const string VALIDATION_NAME_MIN_LIMIT_VIOLATION = "VALIDATION_NAME_MIN_LIMIT_VIOLATION";
    }
}
