export enum ValidationErrorCode {
  VALIDATION_ACCOUNT_FIELD_REQUIRED = "VALIDATION_ACCOUNT_FIELD_REQUIRED",
  VALIDATION_PASSWORD_FIELD_REQUIRED = "VALIDATION_PASSWORD_FIELD_REQUIRED",
  VALIDATION_EMAIL_FIELD_REQUIRED = "VALIDATION_EMAIL_FIELD_REQUIRED",


}
