name: Backend CI/CD

on:

  push:
    branches: [ "main", "develop" ]
    paths:
      - 'AppointmentSchedulerAPI/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'AppointmentSchedulerAPI/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore AppointmentSchedulerAPI.sln
      working-directory: AppointmentSchedulerAPI

    - name: Restore test project dependencies
      run: dotnet restore 
      working-directory: AppointmentSchedulerAPI

    - name: Build the project
      run: dotnet build --configuration Release
      working-directory: AppointmentSchedulerAPI



  
  # test:
  # Create env file <<         run: | echo "${{ secrets.ENV_FILE }}" > .env and execute docker compose
  #   runs-on: ubuntu-latest
  #   needs: build 
  #   steps:
  #   - name: "Checkout code"
  #     uses: actions/checkout@v2

  #   - name: Set up .NET SDK
  #     uses: actions/setup-dotnet@v3
  #     with:
  #       dotnet-version: '9.0'

  #   - name: Restore dependencies
  #     run: dotnet restore AppointmentSchedulerAPI/AppointmentSchedulerAPI.sln
  #     working-directory: AppointmentSchedulerAPI

  #   - name: Run tests
  #     run: dotnet test --configuration Release --no-build
  #     working-directory: AppointmentSchedulerAPI


  build-image:
    runs-on: ubuntu-latest
    # needs: [test]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image
        run: |
            docker buildx build \
            -f AppointmentSchedulerAPI/Dockerfile \
            --platform linux/amd64 \
            --push \
            --tag adrianc68/appschedulingsystem-app:latest \
            --tag adrianc68/appschedulingsystem-app:${{ github.sha }} \
            AppointmentSchedulerAPI


